const studentData = {
    // "Name": "Johnsoni",
    // "DateOfBirth": "01/01/2019",
    // "Gender": "Female",
    // "FatherName": "Jhon",
    // "MotherName": "Clayain",
    // "FatherOccupation": "Designer",
    // "Email": "Johnsoni@gmail.com",
    // "AdmissionDate": "01/01/2023",
    // "RollNo": "23",
    // "AadharCardNumber": "3333 4444 4444",
    // "Nationality": "Indian",
    // "MotherTongue": "Telugu",
    // "PlaceOfBirth": "India",
    // "Address": "India,Earth,553543",
    // "Class": "LKG",
    // "Section": "A",  
    // "Phone": "9944994488",

    "id": 1,
    "firstName": "John",
    "middleName": "Doe",
    "lastName": "Smith",
    "birthDate": "1990-05-15",
    "nationality": "American",
    "motherTongue": "English",
    "gender": "MALE",
    "address": null,
    "identityProof": "A1234567",
    "mobile": "+1 555-1234",
    "photo": "http://example.com/john_smith_photo.jpg",
    "grade": "A+",
    "createdAt": "2024-01-28T12:30:00",
    "updatedAt": "2024-01-28T12:45:00",
    "createdBy": "admin",
    "updatedBy": "editor",
    "orgId": "org123",
    "branchId": "branch456"
  }

  export default studentData;